USE OCORRENCIA

DECLARE @COD_NATUREZA INT,
@COD_AGENCIA	int

set @COD_AGENCIA = 4


SELECT        
MONTH(TP_ATENDIMENTO.DT_CADASTRO) [MES], 
YEAR(TP_ATENDIMENTO.DT_CADASTRO) [ANO], 
COUNT(TP_ATENDIMENTO.COD_NATUREZA_FINAL) [QUANTIDADE], 
dbo.TA_NATUREZA.DSC_NATUREZA [NATUREZA],
dbo.TA_AGENCIA.NM_SIGLA

FROM            dbo.TP_ATENDIMENTO INNER JOIN
                         dbo.TA_UNIDADE ON dbo.TP_ATENDIMENTO.COD_UNIDADE = dbo.TA_UNIDADE.COD_UNIDADE INNER JOIN
                         dbo.TA_AGENCIA ON dbo.TA_UNIDADE.COD_AGENCIA = dbo.TA_AGENCIA.COD_AGENCIA LEFT OUTER JOIN
                         dbo.TA_NATUREZA ON dbo.TP_ATENDIMENTO.COD_NATUREZA_FINAL = dbo.TA_NATUREZA.COD_NATUREZA
WHERE        
(dbo.TP_ATENDIMENTO.DT_CADASTRO > '2016-02-08 00:00:00') 
AND (dbo.TP_ATENDIMENTO.DT_CADASTRO < '2017-02-08 00:00:00') 
and (dbo.TP_ATENDIMENTO.COD_NATUREZA_FINAL = ISNULL(@COD_NATUREZA,dbo.TP_ATENDIMENTO.COD_NATUREZA_FINAL)) 
and (dbo.TA_AGENCIA.COD_AGENCIA = ISNULL(@COD_AGENCIA,dbo.TA_AGENCIA.COD_AGENCIA)) 
GROUP BY MONTH(TP_ATENDIMENTO.DT_CADASTRO), YEAR(TP_ATENDIMENTO.DT_CADASTRO), dbo.TA_NATUREZA.DSC_NATUREZA,dbo.TA_AGENCIA.NM_SIGLA 
--HAVING (TA_NATUREZA.DSC_NATUREZA) is null
order by 1,2,3 desc 




SELECT 
MONTH(TP_ATENDIMENTO.DT_CADASTRO) [MES], 
YEAR(TP_ATENDIMENTO.DT_CADASTRO) [ANO], 
COUNT(TP_ATENDIMENTO.COD_NATUREZA_FINAL) [QUANTIDADE], 
dbo.TA_NATUREZA.DSC_NATUREZA [NATUREZA],
dbo.TA_AGENCIA.NM_SIGLA
FROM            dbo.TA_UNIDADE INNER JOIN
                         dbo.TP_ATENDIMENTO ON dbo.TA_UNIDADE.COD_UNIDADE = dbo.TP_ATENDIMENTO.COD_UNIDADE INNER JOIN
                         dbo.TA_AGENCIA ON dbo.TA_UNIDADE.COD_AGENCIA = dbo.TA_AGENCIA.COD_AGENCIA INNER JOIN
                         dbo.TA_NATUREZA ON dbo.TP_ATENDIMENTO.COD_NATUREZA_FINAL = dbo.TA_NATUREZA.COD_NATUREZA
WHERE        
--(dbo.TR_TEMPO_RECURSO.COD_TIPO_TEMPO_RECURSO = 2) 
 TP_ATENDIMENTO.DT_CADASTRO > '2016-08-02 00:00:00' 
and TP_ATENDIMENTO.DT_CADASTRO	< '2017-08-02 00:00:00'		
--and (dbo.TP_ATENDIMENTO.COD_NATUREZA_FINAL = ISNULL(@COD_NATUREZA,dbo.TP_ATENDIMENTO.COD_NATUREZA_FINAL)) 
--and (dbo.TA_AGENCIA.COD_AGENCIA = ISNULL(4,dbo.TA_AGENCIA.COD_AGENCIA)) 
GROUP BY MONTH(TP_ATENDIMENTO.DT_CADASTRO), YEAR(TP_ATENDIMENTO.DT_CADASTRO), dbo.TA_NATUREZA.DSC_NATUREZA,dbo.TA_AGENCIA.NM_SIGLA 
--HAVING COUNT((TP_ATENDIMENTO.COD_NATUREZA_FINAL)) <=1
order by 3 desc 




SELECT      dbo.TP_ATENDIMENTO.COD_ATENDIMENTO, dbo.TP_ATENDIMENTO.DT_CADASTRO, dbo.TP_ATENDIMENTO.COD_NATUREZA_FINAL, dbo.TA_NATUREZA.DSC_NATUREZA
FROM        dbo.TP_ATENDIMENTO LEFT OUTER JOIN
			dbo.TA_NATUREZA ON dbo.TP_ATENDIMENTO.COD_NATUREZA_FINAL = dbo.TA_NATUREZA.COD_NATUREZA
			where dbo.TP_ATENDIMENTO.COD_NATUREZA_FINAL is null 








SELECT DISTINCT 
                         TOP (100) PERCENT dbo.TP_ATENDIMENTO.COD_ATENDIMENTO, dbo.TP_ATENDIMENTO.DT_CADASTRO, dbo.TR_TEMPO_RECURSO.COD_TIPO_TEMPO_RECURSO, dbo.TA_TIPO_TEMPO_RECURSO.NM_TIPO_TEMPO_RECURSO, dbo.TP_RECURSO.NM_RECURSO, 
                         dbo.TR_TEMPO_RECURSO.DT_TEMPO_RECURSO, dbo.TA_AGENCIA.COD_AGENCIA, dbo.TA_AGENCIA.NM_SIGLA, dbo.TP_ATENDIMENTO.COD_NATUREZA_FINAL, dbo.TA_NATUREZA.DSC_NATUREZA
FROM            dbo.TR_ATENDIMENTO_RECURSO INNER JOIN
                         dbo.TP_ATENDIMENTO ON dbo.TR_ATENDIMENTO_RECURSO.COD_ATENDIMENTO = dbo.TP_ATENDIMENTO.COD_ATENDIMENTO INNER JOIN
                         dbo.TR_TEMPO_RECURSO ON dbo.TR_ATENDIMENTO_RECURSO.COD_ATENDIMENTO_RECURSO = dbo.TR_TEMPO_RECURSO.COD_ATENDIMENTO_RECURSO INNER JOIN
                         dbo.TA_TIPO_TEMPO_RECURSO ON dbo.TR_TEMPO_RECURSO.COD_TIPO_TEMPO_RECURSO = dbo.TA_TIPO_TEMPO_RECURSO.COD_TIPO_TEMPO_RECURSO INNER JOIN
                         dbo.TP_RECURSO ON dbo.TR_ATENDIMENTO_RECURSO.COD_RECURSO = dbo.TP_RECURSO.COD_RECURSO INNER JOIN
                         dbo.TA_AGENCIA ON dbo.TP_RECURSO.COD_AGENCIA = dbo.TA_AGENCIA.COD_AGENCIA LEFT OUTER JOIN
                         dbo.TA_NATUREZA ON dbo.TP_ATENDIMENTO.COD_NATUREZA_FINAL = dbo.TA_NATUREZA.COD_NATUREZA
WHERE        --(dbo.TR_TEMPO_RECURSO.COD_TIPO_TEMPO_RECURSO = 2)


 TP_ATENDIMENTO.DT_CADASTRO > '2016-08-02 00:00:00' 
and TP_ATENDIMENTO.DT_CADASTRO	< '2017-08-02 00:00:00'		
--and (dbo.TP_ATENDIMENTO.COD_NATUREZA_FINAL = ISNULL(@COD_NATUREZA,dbo.TP_ATENDIMENTO.COD_NATUREZA_FINAL)) 
--and (dbo.TA_AGENCIA.COD_AGENCIA = ISNULL(4,dbo.TA_AGENCIA.COD_AGENCIA)) 
ORDER BY TP_ATENDIMENTO.DT_CADASTRO DESC 


